name: Java CI with Gradle

on:
  push:
    branches: ["master"]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.6"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Grant Permissions to gradlew
        run: chmod +x demo/gradlew
      - name: Test
        run: ./demo/gradlew test --tests "*"